/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.wqz.ds.thrift.core;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2017-06-06")
public class PostFace {

  public interface Iface {

    public java.lang.String clientFindAFace(FaceInfo faceInfo, ClientInfo clientInfo) throws org.apache.thrift.TException;

    public java.util.List<ClerkFace> getClerkFaceByStoreId(int storeId) throws org.apache.thrift.TException;

  }

  public interface AsyncIface {

    public void clientFindAFace(FaceInfo faceInfo, ClientInfo clientInfo, org.apache.thrift.async.AsyncMethodCallback<java.lang.String> resultHandler) throws org.apache.thrift.TException;

    public void getClerkFaceByStoreId(int storeId, org.apache.thrift.async.AsyncMethodCallback<java.util.List<ClerkFace>> resultHandler) throws org.apache.thrift.TException;

  }

  public static class Client extends org.apache.thrift.TServiceClient implements Iface {
    public static class Factory implements org.apache.thrift.TServiceClientFactory<Client> {
      public Factory() {}
      public Client getClient(org.apache.thrift.protocol.TProtocol prot) {
        return new Client(prot);
      }
      public Client getClient(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
        return new Client(iprot, oprot);
      }
    }

    public Client(org.apache.thrift.protocol.TProtocol prot)
    {
      super(prot, prot);
    }

    public Client(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TProtocol oprot) {
      super(iprot, oprot);
    }

    public java.lang.String clientFindAFace(FaceInfo faceInfo, ClientInfo clientInfo) throws org.apache.thrift.TException
    {
      send_clientFindAFace(faceInfo, clientInfo);
      return recv_clientFindAFace();
    }

    public void send_clientFindAFace(FaceInfo faceInfo, ClientInfo clientInfo) throws org.apache.thrift.TException
    {
      clientFindAFace_args args = new clientFindAFace_args();
      args.setFaceInfo(faceInfo);
      args.setClientInfo(clientInfo);
      sendBase("clientFindAFace", args);
    }

    public java.lang.String recv_clientFindAFace() throws org.apache.thrift.TException
    {
      clientFindAFace_result result = new clientFindAFace_result();
      receiveBase(result, "clientFindAFace");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "clientFindAFace failed: unknown result");
    }

    public java.util.List<ClerkFace> getClerkFaceByStoreId(int storeId) throws org.apache.thrift.TException
    {
      send_getClerkFaceByStoreId(storeId);
      return recv_getClerkFaceByStoreId();
    }

    public void send_getClerkFaceByStoreId(int storeId) throws org.apache.thrift.TException
    {
      getClerkFaceByStoreId_args args = new getClerkFaceByStoreId_args();
      args.setStoreId(storeId);
      sendBase("getClerkFaceByStoreId", args);
    }

    public java.util.List<ClerkFace> recv_getClerkFaceByStoreId() throws org.apache.thrift.TException
    {
      getClerkFaceByStoreId_result result = new getClerkFaceByStoreId_result();
      receiveBase(result, "getClerkFaceByStoreId");
      if (result.isSetSuccess()) {
        return result.success;
      }
      throw new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.MISSING_RESULT, "getClerkFaceByStoreId failed: unknown result");
    }

  }
  public static class AsyncClient extends org.apache.thrift.async.TAsyncClient implements AsyncIface {
    public static class Factory implements org.apache.thrift.async.TAsyncClientFactory<AsyncClient> {
      private org.apache.thrift.async.TAsyncClientManager clientManager;
      private org.apache.thrift.protocol.TProtocolFactory protocolFactory;
      public Factory(org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.protocol.TProtocolFactory protocolFactory) {
        this.clientManager = clientManager;
        this.protocolFactory = protocolFactory;
      }
      public AsyncClient getAsyncClient(org.apache.thrift.transport.TNonblockingTransport transport) {
        return new AsyncClient(protocolFactory, clientManager, transport);
      }
    }

    public AsyncClient(org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.async.TAsyncClientManager clientManager, org.apache.thrift.transport.TNonblockingTransport transport) {
      super(protocolFactory, clientManager, transport);
    }

    public void clientFindAFace(FaceInfo faceInfo, ClientInfo clientInfo, org.apache.thrift.async.AsyncMethodCallback<java.lang.String> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      clientFindAFace_call method_call = new clientFindAFace_call(faceInfo, clientInfo, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class clientFindAFace_call extends org.apache.thrift.async.TAsyncMethodCall<java.lang.String> {
      private FaceInfo faceInfo;
      private ClientInfo clientInfo;
      public clientFindAFace_call(FaceInfo faceInfo, ClientInfo clientInfo, org.apache.thrift.async.AsyncMethodCallback<java.lang.String> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.faceInfo = faceInfo;
        this.clientInfo = clientInfo;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("clientFindAFace", org.apache.thrift.protocol.TMessageType.CALL, 0));
        clientFindAFace_args args = new clientFindAFace_args();
        args.setFaceInfo(faceInfo);
        args.setClientInfo(clientInfo);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public java.lang.String getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_clientFindAFace();
      }
    }

    public void getClerkFaceByStoreId(int storeId, org.apache.thrift.async.AsyncMethodCallback<java.util.List<ClerkFace>> resultHandler) throws org.apache.thrift.TException {
      checkReady();
      getClerkFaceByStoreId_call method_call = new getClerkFaceByStoreId_call(storeId, resultHandler, this, ___protocolFactory, ___transport);
      this.___currentMethod = method_call;
      ___manager.call(method_call);
    }

    public static class getClerkFaceByStoreId_call extends org.apache.thrift.async.TAsyncMethodCall<java.util.List<ClerkFace>> {
      private int storeId;
      public getClerkFaceByStoreId_call(int storeId, org.apache.thrift.async.AsyncMethodCallback<java.util.List<ClerkFace>> resultHandler, org.apache.thrift.async.TAsyncClient client, org.apache.thrift.protocol.TProtocolFactory protocolFactory, org.apache.thrift.transport.TNonblockingTransport transport) throws org.apache.thrift.TException {
        super(client, protocolFactory, transport, resultHandler, false);
        this.storeId = storeId;
      }

      public void write_args(org.apache.thrift.protocol.TProtocol prot) throws org.apache.thrift.TException {
        prot.writeMessageBegin(new org.apache.thrift.protocol.TMessage("getClerkFaceByStoreId", org.apache.thrift.protocol.TMessageType.CALL, 0));
        getClerkFaceByStoreId_args args = new getClerkFaceByStoreId_args();
        args.setStoreId(storeId);
        args.write(prot);
        prot.writeMessageEnd();
      }

      public java.util.List<ClerkFace> getResult() throws org.apache.thrift.TException {
        if (getState() != org.apache.thrift.async.TAsyncMethodCall.State.RESPONSE_READ) {
          throw new java.lang.IllegalStateException("Method call not finished!");
        }
        org.apache.thrift.transport.TMemoryInputTransport memoryTransport = new org.apache.thrift.transport.TMemoryInputTransport(getFrameBuffer().array());
        org.apache.thrift.protocol.TProtocol prot = client.getProtocolFactory().getProtocol(memoryTransport);
        return (new Client(prot)).recv_getClerkFaceByStoreId();
      }
    }

  }

  public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor<I> implements org.apache.thrift.TProcessor {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(Processor.class.getName());
    public Processor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>>()));
    }

    protected Processor(I iface, java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends Iface> java.util.Map<java.lang.String,  org.apache.thrift.ProcessFunction<I, ? extends org.apache.thrift.TBase>> getProcessMap(java.util.Map<java.lang.String, org.apache.thrift.ProcessFunction<I, ? extends  org.apache.thrift.TBase>> processMap) {
      processMap.put("clientFindAFace", new clientFindAFace());
      processMap.put("getClerkFaceByStoreId", new getClerkFaceByStoreId());
      return processMap;
    }

    public static class clientFindAFace<I extends Iface> extends org.apache.thrift.ProcessFunction<I, clientFindAFace_args> {
      public clientFindAFace() {
        super("clientFindAFace");
      }

      public clientFindAFace_args getEmptyArgsInstance() {
        return new clientFindAFace_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public clientFindAFace_result getResult(I iface, clientFindAFace_args args) throws org.apache.thrift.TException {
        clientFindAFace_result result = new clientFindAFace_result();
        result.success = iface.clientFindAFace(args.faceInfo, args.clientInfo);
        return result;
      }
    }

    public static class getClerkFaceByStoreId<I extends Iface> extends org.apache.thrift.ProcessFunction<I, getClerkFaceByStoreId_args> {
      public getClerkFaceByStoreId() {
        super("getClerkFaceByStoreId");
      }

      public getClerkFaceByStoreId_args getEmptyArgsInstance() {
        return new getClerkFaceByStoreId_args();
      }

      protected boolean isOneway() {
        return false;
      }

      public getClerkFaceByStoreId_result getResult(I iface, getClerkFaceByStoreId_args args) throws org.apache.thrift.TException {
        getClerkFaceByStoreId_result result = new getClerkFaceByStoreId_result();
        result.success = iface.getClerkFaceByStoreId(args.storeId);
        return result;
      }
    }

  }

  public static class AsyncProcessor<I extends AsyncIface> extends org.apache.thrift.TBaseAsyncProcessor<I> {
    private static final org.slf4j.Logger _LOGGER = org.slf4j.LoggerFactory.getLogger(AsyncProcessor.class.getName());
    public AsyncProcessor(I iface) {
      super(iface, getProcessMap(new java.util.HashMap<java.lang.String, org.apache.thrift.AsyncProcessFunction<I, ? extends org.apache.thrift.TBase, ?>>()));
    }

    protected AsyncProcessor(I iface, java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      super(iface, getProcessMap(processMap));
    }

    private static <I extends AsyncIface> java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase,?>> getProcessMap(java.util.Map<java.lang.String,  org.apache.thrift.AsyncProcessFunction<I, ? extends  org.apache.thrift.TBase, ?>> processMap) {
      processMap.put("clientFindAFace", new clientFindAFace());
      processMap.put("getClerkFaceByStoreId", new getClerkFaceByStoreId());
      return processMap;
    }

    public static class clientFindAFace<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, clientFindAFace_args, java.lang.String> {
      public clientFindAFace() {
        super("clientFindAFace");
      }

      public clientFindAFace_args getEmptyArgsInstance() {
        return new clientFindAFace_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<java.lang.String> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<java.lang.String>() { 
          public void onComplete(java.lang.String o) {
            clientFindAFace_result result = new clientFindAFace_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            clientFindAFace_result result = new clientFindAFace_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, clientFindAFace_args args, org.apache.thrift.async.AsyncMethodCallback<java.lang.String> resultHandler) throws org.apache.thrift.TException {
        iface.clientFindAFace(args.faceInfo, args.clientInfo,resultHandler);
      }
    }

    public static class getClerkFaceByStoreId<I extends AsyncIface> extends org.apache.thrift.AsyncProcessFunction<I, getClerkFaceByStoreId_args, java.util.List<ClerkFace>> {
      public getClerkFaceByStoreId() {
        super("getClerkFaceByStoreId");
      }

      public getClerkFaceByStoreId_args getEmptyArgsInstance() {
        return new getClerkFaceByStoreId_args();
      }

      public org.apache.thrift.async.AsyncMethodCallback<java.util.List<ClerkFace>> getResultHandler(final org.apache.thrift.server.AbstractNonblockingServer.AsyncFrameBuffer fb, final int seqid) {
        final org.apache.thrift.AsyncProcessFunction fcall = this;
        return new org.apache.thrift.async.AsyncMethodCallback<java.util.List<ClerkFace>>() { 
          public void onComplete(java.util.List<ClerkFace> o) {
            getClerkFaceByStoreId_result result = new getClerkFaceByStoreId_result();
            result.success = o;
            try {
              fcall.sendResponse(fb, result, org.apache.thrift.protocol.TMessageType.REPLY,seqid);
            } catch (org.apache.thrift.transport.TTransportException e) {
              _LOGGER.error("TTransportException writing to internal frame buffer", e);
              fb.close();
            } catch (java.lang.Exception e) {
              _LOGGER.error("Exception writing to internal frame buffer", e);
              onError(e);
            }
          }
          public void onError(java.lang.Exception e) {
            byte msgType = org.apache.thrift.protocol.TMessageType.REPLY;
            org.apache.thrift.TSerializable msg;
            getClerkFaceByStoreId_result result = new getClerkFaceByStoreId_result();
            if (e instanceof org.apache.thrift.transport.TTransportException) {
              _LOGGER.error("TTransportException inside handler", e);
              fb.close();
              return;
            } else if (e instanceof org.apache.thrift.TApplicationException) {
              _LOGGER.error("TApplicationException inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = (org.apache.thrift.TApplicationException)e;
            } else {
              _LOGGER.error("Exception inside handler", e);
              msgType = org.apache.thrift.protocol.TMessageType.EXCEPTION;
              msg = new org.apache.thrift.TApplicationException(org.apache.thrift.TApplicationException.INTERNAL_ERROR, e.getMessage());
            }
            try {
              fcall.sendResponse(fb,msg,msgType,seqid);
            } catch (java.lang.Exception ex) {
              _LOGGER.error("Exception writing to internal frame buffer", ex);
              fb.close();
            }
          }
        };
      }

      protected boolean isOneway() {
        return false;
      }

      public void start(I iface, getClerkFaceByStoreId_args args, org.apache.thrift.async.AsyncMethodCallback<java.util.List<ClerkFace>> resultHandler) throws org.apache.thrift.TException {
        iface.getClerkFaceByStoreId(args.storeId,resultHandler);
      }
    }

  }

  public static class clientFindAFace_args implements org.apache.thrift.TBase<clientFindAFace_args, clientFindAFace_args._Fields>, java.io.Serializable, Cloneable, Comparable<clientFindAFace_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("clientFindAFace_args");

    private static final org.apache.thrift.protocol.TField FACE_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("faceInfo", org.apache.thrift.protocol.TType.STRUCT, (short)1);
    private static final org.apache.thrift.protocol.TField CLIENT_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("clientInfo", org.apache.thrift.protocol.TType.STRUCT, (short)2);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new clientFindAFace_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new clientFindAFace_argsTupleSchemeFactory();

    public FaceInfo faceInfo; // required
    public ClientInfo clientInfo; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      FACE_INFO((short)1, "faceInfo"),
      CLIENT_INFO((short)2, "clientInfo");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // FACE_INFO
            return FACE_INFO;
          case 2: // CLIENT_INFO
            return CLIENT_INFO;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.FACE_INFO, new org.apache.thrift.meta_data.FieldMetaData("faceInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, FaceInfo.class)));
      tmpMap.put(_Fields.CLIENT_INFO, new org.apache.thrift.meta_data.FieldMetaData("clientInfo", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ClientInfo.class)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(clientFindAFace_args.class, metaDataMap);
    }

    public clientFindAFace_args() {
    }

    public clientFindAFace_args(
      FaceInfo faceInfo,
      ClientInfo clientInfo)
    {
      this();
      this.faceInfo = faceInfo;
      this.clientInfo = clientInfo;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public clientFindAFace_args(clientFindAFace_args other) {
      if (other.isSetFaceInfo()) {
        this.faceInfo = new FaceInfo(other.faceInfo);
      }
      if (other.isSetClientInfo()) {
        this.clientInfo = new ClientInfo(other.clientInfo);
      }
    }

    public clientFindAFace_args deepCopy() {
      return new clientFindAFace_args(this);
    }

    @Override
    public void clear() {
      this.faceInfo = null;
      this.clientInfo = null;
    }

    public FaceInfo getFaceInfo() {
      return this.faceInfo;
    }

    public clientFindAFace_args setFaceInfo(FaceInfo faceInfo) {
      this.faceInfo = faceInfo;
      return this;
    }

    public void unsetFaceInfo() {
      this.faceInfo = null;
    }

    /** Returns true if field faceInfo is set (has been assigned a value) and false otherwise */
    public boolean isSetFaceInfo() {
      return this.faceInfo != null;
    }

    public void setFaceInfoIsSet(boolean value) {
      if (!value) {
        this.faceInfo = null;
      }
    }

    public ClientInfo getClientInfo() {
      return this.clientInfo;
    }

    public clientFindAFace_args setClientInfo(ClientInfo clientInfo) {
      this.clientInfo = clientInfo;
      return this;
    }

    public void unsetClientInfo() {
      this.clientInfo = null;
    }

    /** Returns true if field clientInfo is set (has been assigned a value) and false otherwise */
    public boolean isSetClientInfo() {
      return this.clientInfo != null;
    }

    public void setClientInfoIsSet(boolean value) {
      if (!value) {
        this.clientInfo = null;
      }
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      case FACE_INFO:
        if (value == null) {
          unsetFaceInfo();
        } else {
          setFaceInfo((FaceInfo)value);
        }
        break;

      case CLIENT_INFO:
        if (value == null) {
          unsetClientInfo();
        } else {
          setClientInfo((ClientInfo)value);
        }
        break;

      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case FACE_INFO:
        return getFaceInfo();

      case CLIENT_INFO:
        return getClientInfo();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case FACE_INFO:
        return isSetFaceInfo();
      case CLIENT_INFO:
        return isSetClientInfo();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof clientFindAFace_args)
        return this.equals((clientFindAFace_args)that);
      return false;
    }

    public boolean equals(clientFindAFace_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_faceInfo = true && this.isSetFaceInfo();
      boolean that_present_faceInfo = true && that.isSetFaceInfo();
      if (this_present_faceInfo || that_present_faceInfo) {
        if (!(this_present_faceInfo && that_present_faceInfo))
          return false;
        if (!this.faceInfo.equals(that.faceInfo))
          return false;
      }

      boolean this_present_clientInfo = true && this.isSetClientInfo();
      boolean that_present_clientInfo = true && that.isSetClientInfo();
      if (this_present_clientInfo || that_present_clientInfo) {
        if (!(this_present_clientInfo && that_present_clientInfo))
          return false;
        if (!this.clientInfo.equals(that.clientInfo))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetFaceInfo()) ? 131071 : 524287);
      if (isSetFaceInfo())
        hashCode = hashCode * 8191 + faceInfo.hashCode();

      hashCode = hashCode * 8191 + ((isSetClientInfo()) ? 131071 : 524287);
      if (isSetClientInfo())
        hashCode = hashCode * 8191 + clientInfo.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(clientFindAFace_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetFaceInfo()).compareTo(other.isSetFaceInfo());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetFaceInfo()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.faceInfo, other.faceInfo);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      lastComparison = java.lang.Boolean.valueOf(isSetClientInfo()).compareTo(other.isSetClientInfo());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetClientInfo()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.clientInfo, other.clientInfo);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("clientFindAFace_args(");
      boolean first = true;

      sb.append("faceInfo:");
      if (this.faceInfo == null) {
        sb.append("null");
      } else {
        sb.append(this.faceInfo);
      }
      first = false;
      if (!first) sb.append(", ");
      sb.append("clientInfo:");
      if (this.clientInfo == null) {
        sb.append("null");
      } else {
        sb.append(this.clientInfo);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
      if (faceInfo != null) {
        faceInfo.validate();
      }
      if (clientInfo != null) {
        clientInfo.validate();
      }
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class clientFindAFace_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public clientFindAFace_argsStandardScheme getScheme() {
        return new clientFindAFace_argsStandardScheme();
      }
    }

    private static class clientFindAFace_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<clientFindAFace_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, clientFindAFace_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // FACE_INFO
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.faceInfo = new FaceInfo();
                struct.faceInfo.read(iprot);
                struct.setFaceInfoIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            case 2: // CLIENT_INFO
              if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
                struct.clientInfo = new ClientInfo();
                struct.clientInfo.read(iprot);
                struct.setClientInfoIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, clientFindAFace_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.faceInfo != null) {
          oprot.writeFieldBegin(FACE_INFO_FIELD_DESC);
          struct.faceInfo.write(oprot);
          oprot.writeFieldEnd();
        }
        if (struct.clientInfo != null) {
          oprot.writeFieldBegin(CLIENT_INFO_FIELD_DESC);
          struct.clientInfo.write(oprot);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class clientFindAFace_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public clientFindAFace_argsTupleScheme getScheme() {
        return new clientFindAFace_argsTupleScheme();
      }
    }

    private static class clientFindAFace_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<clientFindAFace_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, clientFindAFace_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetFaceInfo()) {
          optionals.set(0);
        }
        if (struct.isSetClientInfo()) {
          optionals.set(1);
        }
        oprot.writeBitSet(optionals, 2);
        if (struct.isSetFaceInfo()) {
          struct.faceInfo.write(oprot);
        }
        if (struct.isSetClientInfo()) {
          struct.clientInfo.write(oprot);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, clientFindAFace_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(2);
        if (incoming.get(0)) {
          struct.faceInfo = new FaceInfo();
          struct.faceInfo.read(iprot);
          struct.setFaceInfoIsSet(true);
        }
        if (incoming.get(1)) {
          struct.clientInfo = new ClientInfo();
          struct.clientInfo.read(iprot);
          struct.setClientInfoIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class clientFindAFace_result implements org.apache.thrift.TBase<clientFindAFace_result, clientFindAFace_result._Fields>, java.io.Serializable, Cloneable, Comparable<clientFindAFace_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("clientFindAFace_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.STRING, (short)0);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new clientFindAFace_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new clientFindAFace_resultTupleSchemeFactory();

    public java.lang.String success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(clientFindAFace_result.class, metaDataMap);
    }

    public clientFindAFace_result() {
    }

    public clientFindAFace_result(
      java.lang.String success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public clientFindAFace_result(clientFindAFace_result other) {
      if (other.isSetSuccess()) {
        this.success = other.success;
      }
    }

    public clientFindAFace_result deepCopy() {
      return new clientFindAFace_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public java.lang.String getSuccess() {
      return this.success;
    }

    public clientFindAFace_result setSuccess(java.lang.String success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((java.lang.String)value);
        }
        break;

      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof clientFindAFace_result)
        return this.equals((clientFindAFace_result)that);
      return false;
    }

    public boolean equals(clientFindAFace_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(clientFindAFace_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("clientFindAFace_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class clientFindAFace_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public clientFindAFace_resultStandardScheme getScheme() {
        return new clientFindAFace_resultStandardScheme();
      }
    }

    private static class clientFindAFace_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<clientFindAFace_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, clientFindAFace_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
                struct.success = iprot.readString();
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, clientFindAFace_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          oprot.writeString(struct.success);
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class clientFindAFace_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public clientFindAFace_resultTupleScheme getScheme() {
        return new clientFindAFace_resultTupleScheme();
      }
    }

    private static class clientFindAFace_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<clientFindAFace_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, clientFindAFace_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          oprot.writeString(struct.success);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, clientFindAFace_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.success = iprot.readString();
          struct.setSuccessIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class getClerkFaceByStoreId_args implements org.apache.thrift.TBase<getClerkFaceByStoreId_args, getClerkFaceByStoreId_args._Fields>, java.io.Serializable, Cloneable, Comparable<getClerkFaceByStoreId_args>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getClerkFaceByStoreId_args");

    private static final org.apache.thrift.protocol.TField STORE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("storeId", org.apache.thrift.protocol.TType.I32, (short)1);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new getClerkFaceByStoreId_argsStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new getClerkFaceByStoreId_argsTupleSchemeFactory();

    public int storeId; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      STORE_ID((short)1, "storeId");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 1: // STORE_ID
            return STORE_ID;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    private static final int __STOREID_ISSET_ID = 0;
    private byte __isset_bitfield = 0;
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.STORE_ID, new org.apache.thrift.meta_data.FieldMetaData("storeId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getClerkFaceByStoreId_args.class, metaDataMap);
    }

    public getClerkFaceByStoreId_args() {
    }

    public getClerkFaceByStoreId_args(
      int storeId)
    {
      this();
      this.storeId = storeId;
      setStoreIdIsSet(true);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getClerkFaceByStoreId_args(getClerkFaceByStoreId_args other) {
      __isset_bitfield = other.__isset_bitfield;
      this.storeId = other.storeId;
    }

    public getClerkFaceByStoreId_args deepCopy() {
      return new getClerkFaceByStoreId_args(this);
    }

    @Override
    public void clear() {
      setStoreIdIsSet(false);
      this.storeId = 0;
    }

    public int getStoreId() {
      return this.storeId;
    }

    public getClerkFaceByStoreId_args setStoreId(int storeId) {
      this.storeId = storeId;
      setStoreIdIsSet(true);
      return this;
    }

    public void unsetStoreId() {
      __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __STOREID_ISSET_ID);
    }

    /** Returns true if field storeId is set (has been assigned a value) and false otherwise */
    public boolean isSetStoreId() {
      return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __STOREID_ISSET_ID);
    }

    public void setStoreIdIsSet(boolean value) {
      __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __STOREID_ISSET_ID, value);
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      case STORE_ID:
        if (value == null) {
          unsetStoreId();
        } else {
          setStoreId((java.lang.Integer)value);
        }
        break;

      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case STORE_ID:
        return getStoreId();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case STORE_ID:
        return isSetStoreId();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof getClerkFaceByStoreId_args)
        return this.equals((getClerkFaceByStoreId_args)that);
      return false;
    }

    public boolean equals(getClerkFaceByStoreId_args that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_storeId = true;
      boolean that_present_storeId = true;
      if (this_present_storeId || that_present_storeId) {
        if (!(this_present_storeId && that_present_storeId))
          return false;
        if (this.storeId != that.storeId)
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + storeId;

      return hashCode;
    }

    @Override
    public int compareTo(getClerkFaceByStoreId_args other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetStoreId()).compareTo(other.isSetStoreId());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetStoreId()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.storeId, other.storeId);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
    }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("getClerkFaceByStoreId_args(");
      boolean first = true;

      sb.append("storeId:");
      sb.append(this.storeId);
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
        __isset_bitfield = 0;
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getClerkFaceByStoreId_argsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getClerkFaceByStoreId_argsStandardScheme getScheme() {
        return new getClerkFaceByStoreId_argsStandardScheme();
      }
    }

    private static class getClerkFaceByStoreId_argsStandardScheme extends org.apache.thrift.scheme.StandardScheme<getClerkFaceByStoreId_args> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getClerkFaceByStoreId_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 1: // STORE_ID
              if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
                struct.storeId = iprot.readI32();
                struct.setStoreIdIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getClerkFaceByStoreId_args struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        oprot.writeFieldBegin(STORE_ID_FIELD_DESC);
        oprot.writeI32(struct.storeId);
        oprot.writeFieldEnd();
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getClerkFaceByStoreId_argsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getClerkFaceByStoreId_argsTupleScheme getScheme() {
        return new getClerkFaceByStoreId_argsTupleScheme();
      }
    }

    private static class getClerkFaceByStoreId_argsTupleScheme extends org.apache.thrift.scheme.TupleScheme<getClerkFaceByStoreId_args> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getClerkFaceByStoreId_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetStoreId()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetStoreId()) {
          oprot.writeI32(struct.storeId);
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getClerkFaceByStoreId_args struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          struct.storeId = iprot.readI32();
          struct.setStoreIdIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

  public static class getClerkFaceByStoreId_result implements org.apache.thrift.TBase<getClerkFaceByStoreId_result, getClerkFaceByStoreId_result._Fields>, java.io.Serializable, Cloneable, Comparable<getClerkFaceByStoreId_result>   {
    private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("getClerkFaceByStoreId_result");

    private static final org.apache.thrift.protocol.TField SUCCESS_FIELD_DESC = new org.apache.thrift.protocol.TField("success", org.apache.thrift.protocol.TType.LIST, (short)0);

    private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new getClerkFaceByStoreId_resultStandardSchemeFactory();
    private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new getClerkFaceByStoreId_resultTupleSchemeFactory();

    public java.util.List<ClerkFace> success; // required

    /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
    public enum _Fields implements org.apache.thrift.TFieldIdEnum {
      SUCCESS((short)0, "success");

      private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

      static {
        for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
          byName.put(field.getFieldName(), field);
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, or null if its not found.
       */
      public static _Fields findByThriftId(int fieldId) {
        switch(fieldId) {
          case 0: // SUCCESS
            return SUCCESS;
          default:
            return null;
        }
      }

      /**
       * Find the _Fields constant that matches fieldId, throwing an exception
       * if it is not found.
       */
      public static _Fields findByThriftIdOrThrow(int fieldId) {
        _Fields fields = findByThriftId(fieldId);
        if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
        return fields;
      }

      /**
       * Find the _Fields constant that matches name, or null if its not found.
       */
      public static _Fields findByName(java.lang.String name) {
        return byName.get(name);
      }

      private final short _thriftId;
      private final java.lang.String _fieldName;

      _Fields(short thriftId, java.lang.String fieldName) {
        _thriftId = thriftId;
        _fieldName = fieldName;
      }

      public short getThriftFieldId() {
        return _thriftId;
      }

      public java.lang.String getFieldName() {
        return _fieldName;
      }
    }

    // isset id assignments
    public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
    static {
      java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
      tmpMap.put(_Fields.SUCCESS, new org.apache.thrift.meta_data.FieldMetaData("success", org.apache.thrift.TFieldRequirementType.DEFAULT, 
          new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
              new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ClerkFace.class))));
      metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
      org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(getClerkFaceByStoreId_result.class, metaDataMap);
    }

    public getClerkFaceByStoreId_result() {
    }

    public getClerkFaceByStoreId_result(
      java.util.List<ClerkFace> success)
    {
      this();
      this.success = success;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public getClerkFaceByStoreId_result(getClerkFaceByStoreId_result other) {
      if (other.isSetSuccess()) {
        java.util.List<ClerkFace> __this__success = new java.util.ArrayList<ClerkFace>(other.success.size());
        for (ClerkFace other_element : other.success) {
          __this__success.add(new ClerkFace(other_element));
        }
        this.success = __this__success;
      }
    }

    public getClerkFaceByStoreId_result deepCopy() {
      return new getClerkFaceByStoreId_result(this);
    }

    @Override
    public void clear() {
      this.success = null;
    }

    public int getSuccessSize() {
      return (this.success == null) ? 0 : this.success.size();
    }

    public java.util.Iterator<ClerkFace> getSuccessIterator() {
      return (this.success == null) ? null : this.success.iterator();
    }

    public void addToSuccess(ClerkFace elem) {
      if (this.success == null) {
        this.success = new java.util.ArrayList<ClerkFace>();
      }
      this.success.add(elem);
    }

    public java.util.List<ClerkFace> getSuccess() {
      return this.success;
    }

    public getClerkFaceByStoreId_result setSuccess(java.util.List<ClerkFace> success) {
      this.success = success;
      return this;
    }

    public void unsetSuccess() {
      this.success = null;
    }

    /** Returns true if field success is set (has been assigned a value) and false otherwise */
    public boolean isSetSuccess() {
      return this.success != null;
    }

    public void setSuccessIsSet(boolean value) {
      if (!value) {
        this.success = null;
      }
    }

    public void setFieldValue(_Fields field, java.lang.Object value) {
      switch (field) {
      case SUCCESS:
        if (value == null) {
          unsetSuccess();
        } else {
          setSuccess((java.util.List<ClerkFace>)value);
        }
        break;

      }
    }

    public java.lang.Object getFieldValue(_Fields field) {
      switch (field) {
      case SUCCESS:
        return getSuccess();

      }
      throw new java.lang.IllegalStateException();
    }

    /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
    public boolean isSet(_Fields field) {
      if (field == null) {
        throw new java.lang.IllegalArgumentException();
      }

      switch (field) {
      case SUCCESS:
        return isSetSuccess();
      }
      throw new java.lang.IllegalStateException();
    }

    @Override
    public boolean equals(java.lang.Object that) {
      if (that == null)
        return false;
      if (that instanceof getClerkFaceByStoreId_result)
        return this.equals((getClerkFaceByStoreId_result)that);
      return false;
    }

    public boolean equals(getClerkFaceByStoreId_result that) {
      if (that == null)
        return false;
      if (this == that)
        return true;

      boolean this_present_success = true && this.isSetSuccess();
      boolean that_present_success = true && that.isSetSuccess();
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      return true;
    }

    @Override
    public int hashCode() {
      int hashCode = 1;

      hashCode = hashCode * 8191 + ((isSetSuccess()) ? 131071 : 524287);
      if (isSetSuccess())
        hashCode = hashCode * 8191 + success.hashCode();

      return hashCode;
    }

    @Override
    public int compareTo(getClerkFaceByStoreId_result other) {
      if (!getClass().equals(other.getClass())) {
        return getClass().getName().compareTo(other.getClass().getName());
      }

      int lastComparison = 0;

      lastComparison = java.lang.Boolean.valueOf(isSetSuccess()).compareTo(other.isSetSuccess());
      if (lastComparison != 0) {
        return lastComparison;
      }
      if (isSetSuccess()) {
        lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.success, other.success);
        if (lastComparison != 0) {
          return lastComparison;
        }
      }
      return 0;
    }

    public _Fields fieldForId(int fieldId) {
      return _Fields.findByThriftId(fieldId);
    }

    public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
      scheme(iprot).read(iprot, this);
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
      scheme(oprot).write(oprot, this);
      }

    @Override
    public java.lang.String toString() {
      java.lang.StringBuilder sb = new java.lang.StringBuilder("getClerkFaceByStoreId_result(");
      boolean first = true;

      sb.append("success:");
      if (this.success == null) {
        sb.append("null");
      } else {
        sb.append(this.success);
      }
      first = false;
      sb.append(")");
      return sb.toString();
    }

    public void validate() throws org.apache.thrift.TException {
      // check for required fields
      // check for sub-struct validity
    }

    private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
      try {
        write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
      try {
        read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
      } catch (org.apache.thrift.TException te) {
        throw new java.io.IOException(te);
      }
    }

    private static class getClerkFaceByStoreId_resultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getClerkFaceByStoreId_resultStandardScheme getScheme() {
        return new getClerkFaceByStoreId_resultStandardScheme();
      }
    }

    private static class getClerkFaceByStoreId_resultStandardScheme extends org.apache.thrift.scheme.StandardScheme<getClerkFaceByStoreId_result> {

      public void read(org.apache.thrift.protocol.TProtocol iprot, getClerkFaceByStoreId_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TField schemeField;
        iprot.readStructBegin();
        while (true)
        {
          schemeField = iprot.readFieldBegin();
          if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
            break;
          }
          switch (schemeField.id) {
            case 0: // SUCCESS
              if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
                {
                  org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                  struct.success = new java.util.ArrayList<ClerkFace>(_list0.size);
                  ClerkFace _elem1;
                  for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                  {
                    _elem1 = new ClerkFace();
                    _elem1.read(iprot);
                    struct.success.add(_elem1);
                  }
                  iprot.readListEnd();
                }
                struct.setSuccessIsSet(true);
              } else { 
                org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
              }
              break;
            default:
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
          }
          iprot.readFieldEnd();
        }
        iprot.readStructEnd();

        // check for required fields of primitive type, which can't be checked in the validate method
        struct.validate();
      }

      public void write(org.apache.thrift.protocol.TProtocol oprot, getClerkFaceByStoreId_result struct) throws org.apache.thrift.TException {
        struct.validate();

        oprot.writeStructBegin(STRUCT_DESC);
        if (struct.success != null) {
          oprot.writeFieldBegin(SUCCESS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.success.size()));
            for (ClerkFace _iter3 : struct.success)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
        oprot.writeFieldStop();
        oprot.writeStructEnd();
      }

    }

    private static class getClerkFaceByStoreId_resultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
      public getClerkFaceByStoreId_resultTupleScheme getScheme() {
        return new getClerkFaceByStoreId_resultTupleScheme();
      }
    }

    private static class getClerkFaceByStoreId_resultTupleScheme extends org.apache.thrift.scheme.TupleScheme<getClerkFaceByStoreId_result> {

      @Override
      public void write(org.apache.thrift.protocol.TProtocol prot, getClerkFaceByStoreId_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet optionals = new java.util.BitSet();
        if (struct.isSetSuccess()) {
          optionals.set(0);
        }
        oprot.writeBitSet(optionals, 1);
        if (struct.isSetSuccess()) {
          {
            oprot.writeI32(struct.success.size());
            for (ClerkFace _iter4 : struct.success)
            {
              _iter4.write(oprot);
            }
          }
        }
      }

      @Override
      public void read(org.apache.thrift.protocol.TProtocol prot, getClerkFaceByStoreId_result struct) throws org.apache.thrift.TException {
        org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
        java.util.BitSet incoming = iprot.readBitSet(1);
        if (incoming.get(0)) {
          {
            org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
            struct.success = new java.util.ArrayList<ClerkFace>(_list5.size);
            ClerkFace _elem6;
            for (int _i7 = 0; _i7 < _list5.size; ++_i7)
            {
              _elem6 = new ClerkFace();
              _elem6.read(iprot);
              struct.success.add(_elem6);
            }
          }
          struct.setSuccessIsSet(true);
        }
      }
    }

    private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
      return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
    }
  }

}
